--1

CREATE TABLESPACE tbsp1 DATAFILE 'tbsc1_data.dbf' SIZE 1M;
CREATE TABLESPACE tbsp2 DATAFILE 'tbsc2_data.dbf' SIZE 1M;

--2
CREATE USER SPACE_USER IDENTIFIED BY SPACE123;
ALTER USER SPACE_USER QUOTA 1M ON TBSP1;
ALTER USER SPACE_USER QUOTA 1M ON TBSP2;
GRANT CREATE SESSION TO SPACE_USER;
GRANT CREATE TABLE TO SPACE_USER;

--3
CREATE TABLE DEPARTMENT(
    ID INT PRIMARY KEY,
    NAME VARCHAR2(200)
) TABLESPACE tbsp1;

CREATE TABLE STUDENT(
    NAME VARCHAR2(200),
    ID INT PRIMARY KEY,
    DEPARTMENT INT,
    FOREIGN KEY(DEPARTMENT) REFERENCES DEPARTMENT
) TABLESPACE tbsp1;

--4
CREATE TABLE COURSE(
    CODE INT PRIMARY KEY,
    NAME VARCHAR2(200),
    CREDIT NUMBER(1,2),
    OFFER_BY INT,
    FOREIGN KEY(OFFER_BY) REFERENCES DEPARTMENT
) TABLESPACE tbsp2;

--5
INSERT INTO DEPARTMENT VALUES(1, 'CSE');
INSERT INTO DEPARTMENT VALUES(2, 'EEE');
INSERT INTO DEPARTMENT VALUES(3, 'MPE');
INSERT INTO DEPARTMENT VALUES(4, 'CEE');
INSERT INTO DEPARTMENT VALUES(0, 'BTM');

begin
    FOR ID_COUNTER IN 1..10000 LOOP 
        insert into STUDENT (ID, DEPARTMENT)
        values (ID_COUNTER, MOD(ID_COUNTER, 5));
    END LOOP;
end;
/

ALTER DATABASE
DATAFILE 'tbsc1_data.dbf' RESIZE 15m;

begin
    FOR ID_COUNTER IN 4000..4999 LOOP 
        insert into COURSE (CODE, OFFER_BY)
        values (ID_COUNTER, MOD(ID_COUNTER, 5));
    END LOOP;
end;
/

--6
SELECT tablespace_name , bytes/1024/1024 MB FROM dba_free_space
WHERE tablespace_name ='TBSP1';

SELECT tablespace_name , bytes/1024/1024 MB FROM dba_free_space
WHERE tablespace_name ='TBSP2';

--7
ALTER TABLESPACE tbsp1 ADD DATAFILE 'tbsc3_data.dbf' SIZE 1m;

--8
ALTER DATABASE
DATAFILE 'tbsc2_data.dbf' RESIZE 15m;

--9
SELECT TABLESPACE_NAME, SUM(BYTES)/1024/1024 MB 
FROM DBA_DATA_FILES WHERE TABLESPACE_NAME = 'TBSP1' group BY TABLESPACE_NAME; 
SELECT TABLESPACE_NAME, SUM(BYTES)/1024/1024 MB 
FROM DBA_DATA_FILES WHERE TABLESPACE_NAME = 'TBSP2' group BY TABLESPACE_NAME; 

--10
DROP TABLESPACE TBSP1 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

--11
DROP TABLESPACE TBSP2 INCLUDING CONTENTS KEEP DATAFILES CASCADE CONSTRAINTS;



----ADDITIONAL TASKS--

SELECT tablespace_name FROM DBA_DATA_FILES;

select table_name,tablespace_name from dba_tables where owner = 'NIBIR_200042102'
order by table_name;