--15.11
DROP TABLE CITIZEN;
DROP TABLE SALARY;
DROP TABLE AIRPORTSLOG;
CREATE TABLE CITIZEN(
    ID INT,
    NAME VARCHAR2(20),
    DOB DATE
);

CREATE TABLE SALARY(
    CID INT,
    DT DATE,
    AMOUNT NUMBER
);


CREATE TABLE AIRPORTSLOG(
    DT DATE,
    TP VARCHAR2(13) CONSTRAINT AIR_TYPE CHECK (TP IN('DEPARTURE', 'ARRIVAL')),
    PNAME VARCHAR2(25)
);

CREATE OR REPLACE FUNCTION STATUS_EVALUATION(ID )