SET SERVEROUPUT ON

CREATE OR REPLACE PROCEDURE BUDGET_INC 
AS
    X NUMBER DEFAULT 0;
BEGIN
    UPDATE DEPARTMENT SET BUDGET = BUDGET - 0.10*BUDGET WHERE BUDGET > 99999;

    FOR I IN (SELECT * FROM DEPARTMENT) LOOP
        IF I.BUDGET <= 99999 THEN
            X := X + 1;
        END IF;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE(X);
END;
/

BEGIN
    BUDGET_INC;
END;
/

CREATE OR REPLACE PROCEDURE INSTRUCTOR_TIME(WEEK_DAY IN varchar2, START_TIME IN NUMBER, END_TIME IN NUMBER)
AS 
    INSTRUCTOR_NAME varchar2(20);
BEGIN
    SELECT NAME INTO INSTRUCTOR_NAME FROM instructor WHERE ID =
    (SELECT ID FROM teaches WHERE course_id = 
    (SELECT course_id FROM SECTION WHERE time_slot_id = 
    (SELECT time_slot_id FROM time_slot T WHERE day = SUBSTR(WEEK_DAY, 1,2) AND 
    T.start_hr = START_TIME
    AND T.end_hr = END_TIME)));

    DBMS_OUTPUT.PUT_LINE(INSTRUCTOR_NAME);

END;
/
