CREATE OR REPLACE VIEW 
Advisor_Selection AS 
SELECT ID, name, dept_name
FROM instructor;

CREATE OR REPLACE VIEW Student_Count AS
SELECT max(name) AS max_name, count(s_ID) AS num_S_ID
 FROM Advisor_Selection,
advisor WHERE i_ID = ID GROUP BY i_ID; 


CREATE ROLE STUDENT;
GRANT SELECT ON Advisor_Selection TO STUDENT;
GRANT SELECT ON course TO STUDENT;

CREATE ROLE course_teacher;
GRANT SELECT ON student TO course_teacher;
GRANT SELECT ON course TO course_teacher;

CREATE ROLE HEAD;
GRANT course_teacher to HEAD;
GRANT INSERT ON instructor TO HEAD;

CREATE ROLE ADMINISTRATOR;
GRANT SELECT ON department TO ADMINISTRATOR;
GRANT SELECT ON instructor TO ADMINISTRATOR;

CREATE OR REPLACE VIEW DEPARTMENT_BUDGET AS
SELECT budget FROM department;
GRANT UPDATE ON DEPARTMENT_BUDGET TO ADMINISTRATOR;


CREATE USER ABC IDENTIFIED BY cse_200042102;
GRANT STUDENT TO ABC;

CREATE USER X_LECTURER IDENTIFIED BY cse_17_109;
GRANT course_teacher TO X_LECTURER;

CREATE USER Prof_X IDENTIFIED BY cse_head_2022;
GRANT HEAD TO Prof_X;

CREATE USER X_operator IDENTIFIED BY admins;
GRANT ADMINISTRATOR TO X_operator;



GRANT CREATE SESSION TO ABC;
GRANT CREATE SESSION TO X_LECTURER;
GRANT CREATE SESSION TO Prof_X;
GRANT CREATE SESSION TO X_operator;

conn ABC/cse_200042102

SELECT ID, name, dept_name FROM 
NIBIR_200042102.Advisor_Selection; 
SELECT * FROM 
NIBIR_200042102.course; 

conn X_LECTURER/cse_17_109

SELECT * FROM 
NIBIR_200042102.student; 
SELECT * FROM 
NIBIR_200042102.course; 

conn Prof_X/cse_head_2022

INSERT INTO NIBIR_200042102.instructor 
values('12345', 'Gilbert', 'Comp. Sci.', '50000');

conn X_operator/admins

SELECT * FROM 
NIBIR_200042102.department; 
SELECT * FROM 
NIBIR_200042102.instructor;

UPDATE NIBIR_200042102.department 
SET budget = '80000' WHERE dept_name = 'Biology';